package org.ow2.mind.adl;

import static org.ow2.mind.PathHelper.fullyQualifiedNameToPath;

import org.objectweb.fractal.adl.Definition;

import com.google.inject.Inject;
import com.google.inject.name.Named;

public class OptimizedDefinitionMacroSourceGenerator extends DefinitionIncSourceGenerator {

	/** The name to be used to inject the templateGroupName used by this class. */
	public static final String    TEMPLATE_NAME    = "optim.definitions.implementations.optimizedmacro";

	/** The default templateGroupName used by this class. */
	public static final String    DEFAULT_TEMPLATE = "st.optim.definitions.implementations.OptimizedMacro";

	protected static final String FILE_EXT         = ".macro";

	/**
	 * This class is used to override the standard definition Macro.stc by our one.
	 * This is mostly needed by the single-itf plugin.
	 * @param templateGroupName
	 */
	@Inject
	protected OptimizedDefinitionMacroSourceGenerator(@Named(TEMPLATE_NAME) String templateGroupName) {
		super(templateGroupName);
	}

	// ---------------------------------------------------------------------------
	// public static methods
	// ---------------------------------------------------------------------------

	/**
	 * A static method that returns the name of the file that is generated by this
	 * component for the given {@link Definition};
	 * 
	 * @param definition a {@link Definition} node.
	 * @return the name of the file that is generated by this component for the
	 *         given {@link Definition};
	 */
	public static String getMacroFileName(final Definition definition) {
		return fullyQualifiedNameToPath(definition.getName(), FILE_EXT);
	}

	// ---------------------------------------------------------------------------
	// Overridden method
	// ---------------------------------------------------------------------------

	@Override
	protected String getOutputFileName(final Definition definition) {
		return getMacroFileName(definition);
	}

}
